export const ROUTES = {
  PUBLIC: {
    LOGIN: "/login",
    REGISTER: "/cadastro",
    EXTERNAL_PASSENGER_FORM: "/cadastro-passageiro/:motoristaId",
    SPLASH: "/splash",
    ROOT: "/",
    PRIVACY_POLICY: "/politica-de-privacidade",
    TERMS_OF_USE: "/termos-de-uso",
    EXTERNAL_CHECKOUT_BRIDGE: "/checkout-externo",
  },
  PRIVATE: {
    RESPONSAVEL: {
      ROOT: "/responsavel/*",
      HOME: "/responsavel/carteirinha",
      SELECT: "/responsavel/selecionar",
    },
    ADMIN: {
      ROOT: "/admin",
      DASHBOARD: "/admin/dashboard",
      USERS: "/admin/usuarios",
      USER_DETAILS: "/admin/usuarios/:id",
      SETTINGS: "/admin/configuracoes",
      CALCULATOR: "/admin/calculadora",
      LOGIN_ATTEMPTS: "/admin/tentativas-login",
      ACTIVITY_HISTORY: "/admin/atividades",
      EVOLUTION_INSTANCES: "/admin/evolution",
      BLOG: "/admin/blog",
    },
    MOTORISTA: {
      HOME: "/inicio",
      PASSENGERS: "/alunos",
      PASSENGER_DETAILS: "/alunos/:passageiro_id",
      BILLING: "/parcelas",
      SCHOOLS: "/escolas",
      VEHICLES: "/veiculos",
      EXPENSES: "/gastos",
      REPORTS: "/relatorios",
      CONTRACTS: "/contratos",
      SUBSCRIPTION: "/assinatura",
      ROUTES: "/rotas",
      TEAM: "/equipe",
      ROUTE_SETUP: "/rotas/configurar",
      ROUTE_EDIT: "/rotas/configurar/:id",
      ROUTE_EXECUTE: "/rotas/executar/:id",
      ROUTE_DETAILS: "/rotas/detalhes/:id",
      BIRTHDAYS: "/aniversariantes",
      ACCOUNT: "/conta",
    }
  }
} as const;
