export enum UserType {
  ADMIN = "admin",
  MOTORISTA = "motorista",
  RESPONSAVEL = "responsavel",
  ESCOLA = "escola"
}

export enum CobrancaStatus {
  PAGO = "pago",
  PENDENTE = "pendente"
}

export enum RepasseState {
  CRIADO = 'CRIADO',
  DECODIFICANDO = 'DECODIFICANDO',
  DECODIFICADO = 'DECODIFICADO',
  SUBMETIDO = 'SUBMETIDO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  EM_LIQUIDACAO = 'EM_LIQUIDACAO',
  LIQUIDADO = 'LIQUIDADO',
  ERRO_DECODIFICACAO = 'ERRO_DECODIFICACAO',
  ERRO_TRANSFERENCIA = 'ERRO_TRANSFERENCIA',
  EXPIRADO = 'EXPIRADO',
  CANCELADO = 'CANCELADO',
}

export enum CobrancaOrigem {
  MANUAL = "manual",
  AUTOMATICA = "automatica",
}

export enum WhatsappStatus {
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  CONNECTING = "CONNECTING",
  UNKNOWN = "UNKNOWN",
  NOT_FOUND = "NOT_FOUND"
}

export enum AssinaturaStatus {
  ATIVA = "ativa",
  TRIAL = "trial",
  SUSPENSA = "suspensa",
  PENDENTE_PAGAMENTO = "pendente_pagamento",
  CANCELADA = "cancelada"
}

export enum AssinaturaCobrancaStatus {
  PAGO = "pago",
  PENDENTE_PAGAMENTO = "pendente_pagamento",
  CANCELADA = "cancelada"
}

export enum AssinaturaBillingType {
  SUBSCRIPTION = "subscription",
  UPGRADE_PLAN = "upgrade_plan",
  UPGRADE = "upgrade",
  DOWNGRADE = "downgrade",
  ACTIVATION = "activation",
  EXPANSION = "expansion",
  RENEWAL = "renewal",
}

export enum PixKeyStatus {
  VALIDADA = "VALIDADA",
  NAO_CADASTRADA = "NAO_CADASTRADA",
  FALHA_VALIDACAO = "FALHA_VALIDACAO",
  PENDENTE_VALIDACAO = "PENDENTE_VALIDACAO",
  INVALIDADA_POS_FALHA = "INVALIDADA_POS_FALHA"
}

export enum CobrancaTipoPagamento {
  DINHEIRO = "dinheiro",
  PIX = "pix",
  TRANSFERENCIA = "transferencia",
  BOLETO = "boleto",
  CARTAO = "cartao"
}

export enum PassageiroFormModes {
  CREATE = "create",
  EDIT = "edit",
  FINALIZE = "finalize"
}

export enum PlanSalesContext {
  UPGRADE = "upgrade",
  REGISTER = "register",
  EXPANSION = "expansion",
  UPGRADE_AUTO = "upgrade_auto",
  TRIAL_CONVERSION = "trial_conversion"
}

export enum ContratoStatus {
  PENDENTE = "pendente",
  ASSINADO = "assinado",
  SUBSTITUIDO = "substituido"
}

export enum PassageiroModalidade {
  IDA = "ida",
  VOLTA = "volta",
  IDA_VOLTA = "ida_volta"
}

export enum PassageiroGenero {
  MASCULINO = "masculino",
  FEMININO = "feminino",
  PREFIRO_NAO_INFORMAR = "prefiro_nao_informar"
}

export enum ParentescoResponsavel {
  PAI = "pai",
  MAE = "mae",
  AVO = "avo",
  TIO = "tio",
  IRMAO = "irmao",
  PRIMO = "primo",
  PADRASTRO = "padrastro",
  MADRASTA = "madrasta",
  RESPONSAVEL_LEGAL = "responsavel_legal",
  OUTRO = "outro"
}

export enum AtividadeEntidadeTipo {
  COBRANCA = "COBRANCA",
  PASSAGEIRO = "PASSAGEIRO",
  USUARIO = "USUARIO",
  GASTO = "GASTO",
  VEICULO = "VEICULO",
  ESCOLA = "ESCOLA",
  ASSINATURA = "ASSINATURA",
  CONTRATO = "CONTRATO"
}

export enum AtividadeAcao {
  // Financeiro
  COBRANCA_CRIADA = "COBRANCA_CRIADA",
  COBRANCA_EDITADA = "COBRANCA_EDITADA",
  COBRANCA_EXCLUIDA = "COBRANCA_EXCLUIDA",
  PAGAMENTO_MANUAL = "PAGAMENTO_MANUAL",
  PAGAMENTO_REVERTIDO = "PAGAMENTO_REVERTIDO",
  BAIXA_BANCARIA = "BAIXA_BANCARIA",
  NOTIFICACAO_WHATSAPP = "NOTIFICACAO_WHATSAPP",
  CONFIG_LEMBRETE = "CONFIG_LEMBRETE",

  // Passageiro
  PASSAGEIRO_CRIADO = "PASSAGEIRO_CRIADO",
  PASSAGEIRO_EDITADO = "PASSAGEIRO_EDITADO",
  PASSAGEIRO_STATUS = "PASSAGEIRO_STATUS",
  PASSAGEIRO_EXCLUIDO = "PASSAGEIRO_EXCLUIDO",
  PRE_CADASTRO_CONCLUIDO = "PRE_CADASTRO_CONCLUIDO",

  // Perfil / Sistema
  CHAVE_PIX_ALTERADA = "CHAVE_PIX_ALTERADA",
  PERFIL_EDITADO = "PERFIL_EDITADO",
  CONTRATO_CONFIG_EDITADA = "CONTRATO_CONFIG_EDITADA",
  CONTRATO_GERADO = "CONTRATO_GERADO",
  CONTRATO_ASSINADO = "CONTRATO_ASSINADO",
  CONTRATO_EXCLUIDO = "CONTRATO_EXCLUIDO",
  ASSINATURA_UPGRADE = "ASSINATURA_UPGRADE",
  ASSINATURA_PAGAMENTO = "ASSINATURA_PAGAMENTO",
  ASSINATURA_DOWNGRADE = "ASSINATURA_DOWNGRADE",
  ASSINATURA_CANCELADA = "ASSINATURA_CANCELADA",
  USUARIO_EXCLUIDO = "USUARIO_EXCLUIDO",
  USUARIO_SUSPENSO = "USUARIO_SUSPENSO",
  WHATSAPP_STATUS_ALTERADO = "WHATSAPP_STATUS_ALTERADO",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  SENHA_ALTERADA = "SENHA_ALTERADA",
  RECUPERACAO_SENHA = "RECUPERACAO_SENHA",

  // Operacional
  GASTO_REGISTRADO = "GASTO_REGISTRADO",
  GASTO_EDITADO = "GASTO_EDITADO",
  GASTO_EXCLUIDO = "GASTO_EXCLUIDO",
  VEICULO_CRIADO = "VEICULO_CRIADO",
  VEICULO_EDITADO = "VEICULO_EDITADO",
  VEICULO_STATUS = "VEICULO_STATUS",
  VEICULO_EXCLUIDO = "VEICULO_EXCLUIDO",
  ESCOLA_CRIADA = "ESCOLA_CRIADA",
  ESCOLA_EDITADA = "ESCOLA_EDITADA",
  ESCOLA_STATUS = "ESCOLA_STATUS",
  ESCOLA_EXCLUIDA = "ESCOLA_EXCLUIDA",
  
  // Jobs
  COBRANCAS_GERADAS = "COBRANCAS_GERADAS",
  LOG_LIMPEZA = "LOG_LIMPEZA"
}
